name: disease_xception

trainer: training.trainer.xception

model_params:
  image_size: [256, 256]
  num_classes: 10
  dropout: 0.05

training_params:
  batch_size: 32
  seed: 57
  learning_rate: 1e-4
  weight_decay: 1e-2
  # weights:
  # datasets:
  epoch: 2
  patience: 4
